#!/usr/bin/env bash
# Identify the current user from the corporate directory (Active Directory over LDAP)
# and cache the result at ~/.cache/fit/outpost/state/identity.md for other skills.
#
# Generic by design: nothing is hardcoded. The user, realm, and base DN are all
# derived from the existing Kerberos ticket, and the domain controller is found
# via DNS SRV records. Works for any AD domain, on or off VPN, as long as a
# Kerberos ticket exists and a DC is reachable.
#
# Auth uses SASL/GSSAPI against the existing ticket — no password is ever entered.
set -u

CACHE="$HOME/.cache/fit/outpost/state/identity.md"

# 1. Who are we? Take the principal from the Kerberos ticket: USER@REALM.EXAMPLE.COM
princ=$(klist 2>/dev/null | sed -n 's/.*[Pp]rincipal: *//p' | head -1)
if [ -z "$princ" ]; then
  echo "No Kerberos ticket found. Get one first, e.g.:  kinit <user>@<REALM>" >&2
  exit 1
fi
user=${princ%@*}
realm=${princ#*@}

# 2. Realm -> LDAP base DN (REALM.EXAMPLE.COM -> DC=REALM,DC=EXAMPLE,DC=COM)
base=$(printf '%s' "$realm" | awk -F. '{for(i=1;i<=NF;i++) printf "%sDC=%s",(i>1?",":""),$i}')
dom=$(printf '%s' "$realm" | tr '[:upper:]' '[:lower:]')

# 3. Find a reachable domain controller via DNS SRV (msdcs first, then plain ldap)
dc=$(dig +short SRV "_ldap._tcp.dc._msdcs.$dom" | awk 'NR==1{print $4}' | sed 's/\.$//')
[ -z "$dc" ] && dc=$(dig +short SRV "_ldap._tcp.$dom" | awk 'NR==1{print $4}' | sed 's/\.$//')
if [ -z "$dc" ]; then
  echo "Could not find a domain controller for $dom via DNS SRV." >&2
  exit 1
fi

# 4. Look up the current user's record (GSSAPI = use the existing ticket, no password)
attrs="displayName givenName sn company title department employeeID mail telephoneNumber physicalDeliveryOfficeName manager"
rec=$(ldapsearch -Y GSSAPI -LLL -o ldif-wrap=no -H "ldap://$dc" -b "$base" "(sAMAccountName=$user)" $attrs 2>/dev/null)
if [ -z "$rec" ]; then
  echo "No directory record found for '$user' under $base on $dc." >&2
  exit 1
fi

# Pull a single attribute value out of the LDIF record.
field() { printf '%s\n' "$rec" | sed -n "s/^$1: //p" | head -1; }

disp=$(field displayName); gn=$(field givenName); sn=$(field sn)
company=$(field company); title=$(field title); dept=$(field department)
empid=$(field employeeID); mail=$(field mail)
office=$(field physicalDeliveryOfficeName)

# Real name from given+surname, falling back to displayName. Domain from the email.
name="$gn $sn"; name=$(printf '%s' "$name" | sed 's/^ *//;s/ *$//')
[ -z "$name" ] && name="$disp"
domain=$(printf '%s' "$mail" | sed 's/.*@//' | tr '[:upper:]' '[:lower:]')

# 5. Resolve the manager DN to a name, if present. Manager may live in another
#    domain, so query the Global Catalog (port 3268), which is forest-wide.
mgr=$(field manager)
mgr_name=""
if [ -n "$mgr" ]; then
  mgr_name=$(ldapsearch -Y GSSAPI -LLL -o ldif-wrap=no -H "ldap://$dc:3268" -b "$mgr" -s base \
    displayName 2>/dev/null | sed -n 's/^displayName: //p' | head -1)
fi

# 6. Write the cache. Same Name/Email/Domain shape other skills already parse,
#    plus extra fields. Auto-generated — never hand-edited.
mkdir -p "$(dirname "$CACHE")"
{
  echo "# User Identity"
  echo
  echo "Auto-generated by the \`person-identify\` skill from the corporate directory."
  echo "Do not edit by hand — re-run the skill to refresh."
  echo
  echo "- **Name:** $name"
  echo "- **Email:** $mail"
  echo "- **Domain:** $domain"
  echo "- **Title:** $title"
  echo "- **Department:** $dept"
  echo "- **Company:** $company"
  echo "- **Employee ID:** $empid"
  echo "- **Office:** $office"
  [ -n "$mgr_name" ] && echo "- **Manager:** $mgr_name"
} > "$CACHE"

# 7. Show the result.
cat "$CACHE"
echo
echo "(cached at $CACHE)"
